# Generated by Django 5.1.1 on 2024-10-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.PositiveIntegerField()),
                ('prescription_type', models.CharField(choices=[('prescription', 'Prescription'), ('non-prescription', 'Non-Prescription')], max_length=60)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.inventory')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Information',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_name', models.CharField(max_length=100)),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('medication_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.inventory')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.orderinformation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.patient')),
            ],
            options={
                'verbose_name': 'Prescription Activity Log',
                'verbose_name_plural': 'Prescription Activity Logs',
                'ordering': ['created_at'],
            },
        ),
    ]
