# Generated by Django 5.1.2 on 2024-11-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0003_auto_20241016_2223"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("purchase", "Purchase"),
                            ("inventory_add", "Inventory Add"),
                            ("inventory_remove", "Inventory Remove"),
                            ("inventory_update", "Inventory Update"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
