# Generated by Django 5.1.2 on 2024-11-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0004_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_fail", "Login Fail"),
                    ("purchase", "Purchase"),
                    ("inventory_add", "Inventory Add"),
                    ("inventory_remove", "Inventory Remove"),
                    ("inventory_update", "Inventory Update"),
                ],
                max_length=40,
            ),
        ),
    ]
