# Generated by Django 5.1.2 on 2024-11-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0005_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("M", "Manager"),
                    ("P", "Pharmacist"),
                    ("T", "Technician"),
                    ("C", "Cashier"),
                ],
                max_length=2,
            ),
        ),
    ]
