# Generated by Django 5.1.1 on 2024-11-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.inventory'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='webApp.patient'),
        ),
        migrations.AlterField(
            model_name='prescriptionactivitylog',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.inventory'),
        ),
        migrations.AlterField(
            model_name='prescriptionactivitylog',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.orderinformation'),
        ),
        migrations.AlterField(
            model_name='prescriptionactivitylog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.patient'),
        ),
    ]
