# Generated by Django 5.1.1 on 2024-11-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0008_alter_orderinformation_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="medicine",
            new_name="item",
        ),
        migrations.AddField(
            model_name="inventory",
            name="prescription_type",
            field=models.CharField(
                choices=[
                    ("prescription", "Prescription"),
                    ("non-prescription", "Non-Prescription"),
                ],
                default="prescription",
                max_length=60,
            ),
        ),
    ]
